<MenuScreen>:
    canvas.before:
        color:
            rgba: 1,1,0,1
        Rectangle:
            pos:self.pos
            size: self.size
    BoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'
        Label:
             id: 'dota'
            text:'Some Clicker'
             font_name: 'Jost-Italic-VariableFont_wght.ttf'
            color: '#BFB3FF'
            font_size: '40sp'
